repos:
# Formatting
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: check-added-large-files

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

# Linting
-   repo: https://github.com/pylint-dev/pylint
    rev: v3.0.0a6
    hooks:
    -   id: pylint

# Static Analysis
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle

# Unit Tests
-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: python -m unittest discover
        language: python
        'types': [python]
        args: ["-p '*test*.py'"]
        additional_dependencies: []
        pass_filenames: false
